# RuboCop configuration file

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "api_rails/**/*"  # Exclude Rails directory from root RuboCop runs

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout:
  Include:
    - "spec/**/*"
  Enabled: true

Style:
  Include:
    - "spec/**/*"
  Enabled: true

Lint:
  Exclude:
    - "spec/**/*"
  Enabled: true

Naming:
  Exclude:
    - "spec/**/*"
  Enabled: true

Security:
  Exclude:
    - "spec/**/*"
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics:
  Exclude:
    - "spec/**/*"
  Enabled: true
