name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-ruby-${{ matrix.ruby-version }}
          path: coverage
          if-no-files-found: ignore
