name: API Rails CI

on:
  pull_request:
    paths:
      - "api_rails/**"
  push:
    branches: [main]
    paths:
      - "api_rails/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: api_rails

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec brakeman --no-pager
        working-directory: api_rails

      - name: Lint code for consistent style
        run: bundle exec rubocop --config .rubocop-rails.yml -f github
        working-directory: api_rails

      - name: Run Rails health check
        run: bundle exec rails runner "puts 'Rails is working'"
        working-directory: api_rails

      - name: Run tests with coverage
        run: bundle exec rails test
        working-directory: api_rails

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rails-coverage-report
          path: api_rails/coverage/
          if-no-files-found: ignore
